name: Build conan package

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        docker_image:
          - conanio/gcc8
          - conanio/gcc8-armv7
          - conanio/gcc8-armv7hf
          - conanio/gcc8-armv8
          - conanio/gcc9
          - conanio/gcc9-armv7
          - conanio/gcc9-armv7hf
          - conanio/gcc9-armv8
          - conanio/gcc10
          - conanio/gcc10-armv7
          - conanio/gcc10-armv7hf
          - conanio/clang7
          - conanio/clang8
          - conanio/clang9
          - conanio/clang10
          - conanio/clang11
        include:
          - docker_image: conanio/gcc8
            gcc_version: 8
            build_arch: x86_64
          - docker_image: conanio/gcc8-armv7
            gcc_version: 8
            build_arch: armv7
          - docker_image: conanio/gcc8-armv7hf
            gcc_version: 8
            build_arch: armv7hf
          - docker_image: conanio/gcc8-armv8
            gcc_version: 8
            build_arch: armv8

          - docker_image: conanio/gcc9
            gcc_version: 9
            build_arch: x86_64
          - docker_image: conanio/gcc9-armv7
            gcc_version: 9
            build_arch: armv7
          - docker_image: conanio/gcc9-armv7hf
            gcc_version: 9
            build_arch: armv7hf
          - docker_image: conanio/gcc9-armv8
            gcc_version: 9
            build_arch: armv8

          - docker_image: conanio/gcc10
            gcc_version: 10
            build_arch: x86_64
          - docker_image: conanio/gcc10-armv7
            gcc_version: 10
            build_arch: armv7
          - docker_image: conanio/gcc10-armv7hf
            gcc_version: 10
            build_arch: armv7hf

          - docker_image: conanio/clang7
            clang_version: "7.0"
            build_arch: x86_64
          - docker_image: conanio/clang8
            clang_version: 8
            build_arch: x86_64
          - docker_image: conanio/clang9
            clang_version: 9
            build_arch: x86_64
          - docker_image: conanio/clang10
            clang_version: 10
            build_arch: x86_64
          - docker_image: conanio/clang11
            clang_version: 11
            build_arch: x86_64

    runs-on: ubuntu-latest
    env:
      CONAN_USERNAME: "abbyssoul"
      CONAN_LOGIN_USERNAME: "abbyssoul"
      CONAN_PASSWORD: ${{ secrets.conan_key }}
      CONAN_CHANNEL: "stable"
      CONAN_UPLOAD: "https://api.bintray.com/conan/abbyssoul/public-conan"
      CONAN_BUILD_POLICY: outdated
      CONAN_GCC_VERSIONS: ${{ matrix.gcc_version }}
      CONAN_ARCHS: ${{matrix.build_arch}}
      CONAN_CLANG_VERSIONS: ${{matrix.clang_version}}
      CONAN_DOCKER_IMAGE: ${{ matrix.docker_image }}

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@master
        with:
          python-version: '3.7'
      - name: Generating conan user directory
        run: |
          python -m pip install conan conan_package_tools -U
          conan profile new default --detect
          conan user
      - name: Deduce package version from tag
        run: |
          git fetch --depth=1 origin +$GITHUB_REF:$GITHUB_REF
          export CONAN_VERSION=$(git describe --tags)
          echo "CONAN_REFERENCE=libsolace/${CONAN_VERSION}" >> $GITHUB_ENV

      - name: Building and publish the package
        run: python build-conan-package.py

  build-osx:
    runs-on: macOS-latest
    env:
      CONAN_USERNAME: "abbyssoul"
      CONAN_LOGIN_USERNAME: "abbyssoul"
      CONAN_PASSWORD: ${{ secrets.conan_key }}
      CONAN_CHANNEL: "stable"
      CONAN_UPLOAD: "https://api.bintray.com/conan/abbyssoul/public-conan"
      CONAN_APPLE_CLANG_VERSIONS: "11.0"
      CONAN_BUILD_POLICY: outdated

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@master
        with:
          python-version: '3.7'
      - name: Generating conan profile and user directory
        run: |
          python -m pip install conan conan_package_tools -U
          conan profile new default --detect
          conan user
      - name: Deduce package version from tag
        run: |
          git fetch --depth=1 origin +$GITHUB_REF:$GITHUB_REF
          export CONAN_VERSION=$(git describe --tags)
          echo "CONAN_REFERENCE=libsolace/${CONAN_VERSION}" >> $GITHUB_ENV

      - name: Building and publish the package
        run: python build-conan-package.py
