name: Build conan package

on:
  push:
    tags:
    - 'x*'
    branches: [ feature/release-workflow ]

jobs:
  build:
    strategy:
      matrix:
        # gcc_version: [8, 9]
        # build_arch: [x86_64, armv7, armv7hf]

        docker_image:
          # - conanio/gcc8
          # - conanio/gcc8-armv7
          # - conanio/gcc8-armv7hf
          # - conanio/gcc9
          # - conanio/gcc9-armv7
          - conanio/gcc9-armv7hf
          - conanio/clang7
          # - conanio/clang8
          # - conanio/clang9

        include:
          - docker_image: conanio/gcc8
            gcc_version: 8
            build_arch: x86_64
          - docker_image: conanio/gcc8-armv7
            gcc_version: 8
            build_arch: armv7
          - docker_image: conanio/gcc8-armv7hf
            gcc_version: 8
            build_arch: armv7hf
          - docker_image: conanio/gcc9
            gcc_version: 9
            build_arch: x86_64
          - docker_image: conanio/gcc9-armv7
            gcc_version: 9
            build_arch: armv7
          - docker_image: conanio/gcc9-armv7hf
            gcc_version: 9
            build_arch: armv7hf
          - docker_image: conanio/clang7
            clang_version: "7.0"
            build_arch: x86_64
          - docker_image: conanio/clang8
            clang_version: 8
            build_arch: x86_64
          - docker_image: conanio/clang9
            clang_version: 9
            build_arch: x86_64

        #exclude:
         #- os: macOS-latest

    runs-on: ubuntu-latest
    env:
        CONAN_USERNAME: "abbyssoul"
        CONAN_LOGIN_USERNAME: "abbyssoul"
        CONAN_CHANNEL: "stable"
        CONAN_UPLOAD: "https://api.bintray.com/conan/abbyssoul/public-conan"
        CONAN_BUILD_POLICY: outdated
        CONAN_GCC_VERSIONS: ${{ matrix.gcc_version }}
        CONAN_ARCHS: ${{matrix.build_arch}}
        CONAN_CLANG_VERSIONS: ${{matrix.clang_version}}
        CONAN_DOCKER_IMAGE: ${{ matrix.docker_image }}
        # CONAN_STABLE_BRANCH_PATTERN: "release/*"

    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@master
      with:
        python-version: '3.7'
    - name: Generating conan user directory
      run: |
        python -m pip install conan conan_package_tools -U
        conan profile new default --detect
        conan user
    - name: Deduce package version from tag
      run: |
        git fetch --depth=1 origin +$GITHUB_REF:$GITHUB_REF
        export CONAN_VERSION=$(git describe --tags)
        echo "::set-env name=CONAN_REFERENCE::libsolace/${CONAN_VERSION}"

    - name: Building the package
      run: python build.py

  build-osx:
    runs-on: macOS-latest
    env:
        CONAN_USERNAME: "abbyssoul"
        CONAN_LOGIN_USERNAME: "abbyssoul"
        CONAN_CHANNEL: "stable"
        CONAN_UPLOAD: "https://api.bintray.com/conan/abbyssoul/public-conan"
        CONAN_APPLE_CLANG_VERSIONS: "11.0"
        CONAN_BUILD_POLICY: outdated

    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@master
      with:
        python-version: '3.7'
    - name: Generating conan profile and user directory
      run: |
        python -m pip install conan conan_package_tools -U
        conan profile new default --detect
        conan user
    - name: Deduce package version from tag
      run: |
        git fetch --depth=1 origin +$GITHUB_REF:$GITHUB_REF
        export CONAN_VERSION=$(git describe --tags)
        echo "::set-env name=CONAN_REFERENCE::libsolace/${CONAN_VERSION}"

    - name: Building the package
      run: python build.py
