name: Run Unit tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        # TODO: -- windows-latest
        os: [ubuntu-latest, macOS-latest]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - run: python -m pip install cpplint conan -U
    - run: conan profile new default --detect
    - run: conan profile update settings.compiler.libcxx=libstdc++11 default

    - name: configure
      run: ./configure --enable-debug --enable-coverage --enable-sanitizer
    - name: code-check
      run: make codecheck
    - name: make
      run: make
    - name: Unit-test
      run: make test
